// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCollection(arg1:string,arg2:string):Promise<main.JSResp>;

export function GetCollections():Promise<main.JSResp>;

export function GetRequest(arg1:string,arg2:string):Promise<main.JSResp>;

export function Greet(arg1:string):Promise<string>;

export function UpsertRequest(arg1:main.Request):Promise<main.JSResp>;
