// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollection(arg1, arg2) {
  return window['go']['main']['App']['AddCollection'](arg1, arg2);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpsertRequest(arg1) {
  return window['go']['main']['App']['UpsertRequest'](arg1);
}
