// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollection(arg1, arg2) {
  return window['go']['main']['App']['AddCollection'](arg1, arg2);
}

export function AddVariable(arg1, arg2) {
  return window['go']['main']['App']['AddVariable'](arg1, arg2);
}

export function ChoseFile() {
  return window['go']['main']['App']['ChoseFile']();
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequest'](arg1, arg2);
}

export function DeleteVariable(arg1, arg2) {
  return window['go']['main']['App']['DeleteVariable'](arg1, arg2);
}

export function ExportCollection(arg1) {
  return window['go']['main']['App']['ExportCollection'](arg1);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetRequest(arg1, arg2) {
  return window['go']['main']['App']['GetRequest'](arg1, arg2);
}

export function InvokeRequest(arg1) {
  return window['go']['main']['App']['InvokeRequest'](arg1);
}

export function MoveRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveRequest'](arg1, arg2, arg3);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RenameRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameRequest'](arg1, arg2, arg3);
}

export function UpsertRequest(arg1) {
  return window['go']['main']['App']['UpsertRequest'](arg1);
}
