// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCollection(arg1:string,arg2:string):Promise<main.JSResp>;

export function AddVariable(arg1:string,arg2:main.KV):Promise<main.JSResp>;

export function ChoseFile():Promise<main.JSResp>;

export function DeleteCollection(arg1:string):Promise<main.JSResp>;

export function DeleteRequest(arg1:string,arg2:string):Promise<main.JSResp>;

export function DeleteVariable(arg1:string,arg2:string):Promise<main.JSResp>;

export function ExportCollection(arg1:string):Promise<main.JSResp>;

export function GetCollections():Promise<main.JSResp>;

export function GetRequest(arg1:string,arg2:string):Promise<main.JSResp>;

export function InvokeRequest(arg1:main.Request):Promise<main.JSResp>;

export function MoveRequest(arg1:string,arg2:string,arg3:string):Promise<main.JSResp>;

export function RenameCollection(arg1:string,arg2:string):Promise<main.JSResp>;

export function RenameRequest(arg1:string,arg2:string,arg3:string):Promise<main.JSResp>;

export function UpsertRequest(arg1:main.Request):Promise<main.JSResp>;
